### ISSUE TITLE
CP-plugins link is currently dead

### ISSUE THREAD

**Issue by hinerm** [CellProfiler/CellProfiler-plugins#195]
The [`README.md` ](https://github.com/CellProfiler/CellProfiler-plugins/blob/827a3caab367b81722db9f1b8a834bf1743d8e77/README.md) currently has a link to https://cellprofiler.github.io/CellProfiler-plugins, which gives a 404.

**Comment by ErinWeisbart** [comment]
@bethac07 I might need your help figuring this out.

I have the book building and the gh-pages branch deploying, and I thought I had it set up the same way that I set up our DS repos so following that organization, I'd expect the book to deploy to https://cellprofiler.github.io/CellProfiler-plugins but the action says it's deploying to http://cellprofiler.org/CellProfiler-plugins/ (which is 404ing because it's not part of our OpenScholar page). 

Do you know why it's trying to build to cellprofiler.org? Do we have a redirect on cellprofiler.github.io to cellprofiler.org?

**Comment by bethac07** [comment]
We don't have an org-level redirect that I can tell, but we do have the tutorials repo redirecting there, so perhaps that's enough. The documentation here will now point at plugins.cellprofiler.org, will pu tin the necessary changes
